# Generated by Django 3.2.8 on 2021-11-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
