# Generated by Django 3.2.8 on 2021-11-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_alter_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
